os: linux
dist: xenial
language: node_js
node_js:
- '14'

branches:
  only:
    - main
    - dev

before_install:
- npm install -g @angular/cli
install:
- npm install

addons:
  sonarcloud:
    organization: "netcrackergroup2"
    token:
      secure: "m13nj83T+eRYFcYXWrWs4kD7l3ZkgbhJQjgnCbbIKu3sRo4u56BLYs6pPijmM9F03Kqvx5C/PURX0MbU5f2lDg3yaiYrHHUZHz8fb7gcp2BwV1c4tRiSmRGmdCGBhiPYNCQvJiWz/E3SBH80c+pIctzHgeN7SZcMJu0gd7ter1YWRq6II2FLf8RbwV4MzStsXSF7OQ1lheOjrqGTHSNS8jT+fs/isRn0P9C3xRPxj7owWBt81YZpNvRqElIFJXE6GXntAGKRFAUSWkWSdzEkgqNxNZkYQHijswFMbrRjelzVnVs8W6IdWhLHdAoGefCJaon9jgdRb6HIcL3ThPP3ClzZJFOPDqEeeo1ge7ru6iom4Dv9k51Wl2WriZI/78NQO5V6MoNxJLU7JBpSU7wku0fCBcAliFCyy128OjMhoiT25ieHaxJXxytq6WGMEk9rKIcXP+jNWzU2TSsZDFryT7noybLfcz64W6AKlbn0hW0mJ9CLR7f3Ji8Db+rHWLKoqBytNTyYNWTMW0vPvN3WBqSYQ5lN/DNWkDMpQYrcWK9NiDlY+T/z7ymNz9ee40W8ad71v7yIaSdhkBAuh3x7j5H7F2l3107u+CxCfaePGgANg/wr80i0L/CIOf7890aUdi8fMi5F0bnqS+jqbCwLBRHwnlT9iBFm4Rpd4py7pY0="
script:
- sonar-scanner

deploy:
  provider: heroku
  app:
    main: cheetah-test-frontend-prod
    dev: cheetah-test-frontend-dev
  api_key:
    secure: Blbvoh7wsvcwIMuZYd+kkcWSItvMXDfAP+NGRZ5RSvZmaVaMQGUHQ7bw3tP8YqZ8jrDTzCg0BGfyEAzsFKiHTx5gqi1c9d/Vlb5NnlFb4yVYxnJh7rKz5mVKPsCHdM4dIHOI41zxaDJOMBv5GXUcoEbUYvxnDXcXL/Z1BPGCjCd9WkO2MkdW4TkICyalIbp/vUGaPM4rmOy4oGnJBW78wwTXoDAGl4PRjFvkbQUqnhd5mzJ4Ay6osdnmXbAG//iB0eVjuYW7b82Bi+5Jjnk4alur0MqrXumvwxL3b+CkyJbkyMnWlK0YI2XiGy21ZjM1iD335gVqVsBfaU0mvgfvvOjIF2X/Bdtw1+fQd+k/flSk0fVby9P35NPF3bYaAF+h5axAV7QCKOSvvkHiDVal6FnSwCdlQDKsnpdqojnVyqcc9ggM2M9Zna3m60iE0nZR6yPfuHLEg6PnKP8qdWMY6NilbWuD6PuUFrP2TXH774bku/ON0T/l1qrR+R81LdBTfdVeZKCWfubbjdXpxK98BtwIzg2UqDPEDpAID/1mnKIcYiuFxdHYrVkTLAH8Gi6clTHJbgIGoaEkqPb9aUdsZdrzPOJ2x1Wz/50sfxfVG/UyWb0L8gHQxr4xMl17kKoLhFrVcw15yKBUEGtHEFOqsnEZmn3zT1gYIydamqIMMeE=
